.TH "gpg-open" "1" "0.4" "Christoph Souris" ""
.SH "NAME"
.LP 
gpg-open \- Open PGP/GPG files in the dedicated application.
.SH "SYNOPSIS"
.LP 
gpg-open \fIinputfile\fP
.SH "DESCRIPTION"
.LP 
The \fBgpg-open\fP command line utility is used to open a PGP/GPG encrypted file directly in the dedicated application. The file is decrypted/encrypted internally and opened by using the \fBgnome-open\fP command line utility.
.SH "AUTHORS"
.LP 
Christoph Souris (christoph.souris at googlemail.com)
.SH "SEE ALSO"
.LP 
\fBgnome-open\fP
